### ISSUE TITLE
Cannot use PositionControllers_JointTrajectoryController

### ISSUE THREAD

**Issue by zulqarnainhalil** [MerlinLaboratory/ABB_omnicore_ros_driver#20]
Hi,

The package works with VelocityControllers_JointTrajectoryController, but it doesnt work with PositionControllers_JointTrajectoryController. Have this controller file been tested yet?

Thanks.

**Comment by pucciland95** [comment]
Hi, 

I decided to drop the support for the position controller since It is possible to create your own around the velocity one. 

That being said, I think that with some tricks it is still possible to use it. 

In particular, if you look inside the ros_control_omnivore under config/controllers/your_robot there is still the positionController/jointTrajectoryController. If you load that file inside the launcher of the ros_control_omnicore pkg it should work (I think). 

I am sorry that I cannot test it myself but I don't have access to the robot anymore...

I would like finally to notice that the last param that you load in the previously said file "pos_corr_gain" need to be at 1 for the ABB robots to accept both position and (optionally) velocity in feed forward. Check the documentation of EGM for further info. 

Cheers and let me know if you have further problems

**Comment by pucciland95** [comment]
@zulqarnainhalil can you provide me with some feedback? Otherwise I would close the issue for inactivity
